### ISSUE TITLE
CircleCI fails with pip install mkdocs

### ISSUE THREAD

**Issue by OleRoel** [dustinfarris/ember-django-adapter#216]
CI fails in the deployment step, because `sudo pip install mkdocs` seems to have a sub-dependency with "tornado>=5.". Tornado again complains about the following:

```Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).```

This make the deployment fail.

**Comment by benmurden** [comment]
Let me know if I can help with this.

**Comment by OleRoel** [comment]
@benmurden 
Thank you for you offer!
As stated [here](https://github.com/dustinfarris/ember-django-adapter/pull/215#issuecomment-445931482) do I try to set up a CircleCI 2.0 config file on the fork in my repository [here](https://github.com/OleRoel/ember-django-adapter/blob/circleci-20-test/.circleci/config.yml). I am a bloody beginner with CircleCI, so any help is appreciated.

**Comment by OleRoel** [comment]
@benmurden @dustinfarris 
This is _almost_ working on my repository

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout      
      - run: sudo pip install mkdocs
      - run: mkdocs gh-deploy
      
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
```
The deployment step is not working, because the .circleci/config.yml is not part of the gh-pages branch. This leads to the following error in the deploy step:

```bash
#!/bin/sh -eo pipefail
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

I am now looking into the resolution of this issue.

Besides this: any objections against the config above?
