### ISSUE TITLE
testing with multiple versions of ember and ember-data

### ISSUE THREAD

**Issue by benkonrath** [dustinfarris/ember-django-adapter#54]
Now the ED beta 14 and 14.1 are out, we should see if there's a way to test with multiple versions of ember and ember data. @dustinfarris Do you have any ideas on this?

**Comment by dustinfarris** [comment]
It looks like this isn't well supported by npm.  See npm/npm#5499.

We could do something in `circle.yml`, like:

```yml
test:
  override:
    - npm install ember-data@1.0.0-beta.14 && ember test
    - npm install ember-data@1.0.0-beta.14.1 && ember test
```

I'm not sure if this will work.  One of us should try this out on a throw-away branch.
